server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
      timeout: 1d
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      mode: always



logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.memo: DEBUG


secret:
  key: 66eI7JeQ64ukIOumrOy/oCDthqDsv6Drhbgg7Jyg7Jqw7IucIOuztOqzoOyLtuuLpA==