
server:
  servlet:
    session:
      cookie:
        secure: false
        http-only: true
      timeout: 1d
    encoding:
      charset: UTF-8
      force: true


spring:
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3306/memo_application
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
    show-sql: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    com.my.memo: DEBUG